// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSYvbHdYWns3bmhHxt_x3YUyUlSpx7lEs',
    appId: '1:27014676278:web:0fc2ed7fd68881d0af3d97',
    messagingSenderId: '27014676278',
    projectId: 'groceryapp-fdea3',
    authDomain: 'groceryapp-fdea3.firebaseapp.com',
    storageBucket: 'groceryapp-fdea3.appspot.com',
    measurementId: 'G-LK7J1G0HBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbueafmqUZVSDbeGsR2rI3XCXU3j-IKVM',
    appId: '1:27014676278:android:40e470aa9cab41e9af3d97',
    messagingSenderId: '27014676278',
    projectId: 'groceryapp-fdea3',
    storageBucket: 'groceryapp-fdea3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfxD07WUvF0P8A-46Kr72AEzFXDLjvpQg',
    appId: '1:27014676278:ios:31eb13abd77e621baf3d97',
    messagingSenderId: '27014676278',
    projectId: 'groceryapp-fdea3',
    storageBucket: 'groceryapp-fdea3.appspot.com',
    iosBundleId: 'com.example.groceryAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfxD07WUvF0P8A-46Kr72AEzFXDLjvpQg',
    appId: '1:27014676278:ios:f4e94b14789fb318af3d97',
    messagingSenderId: '27014676278',
    projectId: 'groceryapp-fdea3',
    storageBucket: 'groceryapp-fdea3.appspot.com',
    iosBundleId: 'com.example.groceryAppFlutter.RunnerTests',
  );
}
